# Generated by Django 3.2.5 on 2021-07-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_dat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_down',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_rtm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_up',
            field=models.BooleanField(default=False),
        ),
    ]
