# Generated by Django 3.2.5 on 2021-07-22 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20210718_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 22)),
        ),
    ]
