# Generated by Django 3.2.5 on 2021-07-23 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_bid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
