# Generated by Django 3.2.5 on 2021-07-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
