# Generated by Django 3.2.5 on 2021-07-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
