# Generated by Django 3.2.5 on 2021-07-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_alter_reserve_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
