# Generated by Django 3.2.5 on 2021-07-18 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_clearedreserveup_clearentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearedreserveup',
            name='time',
        ),
        migrations.AddField(
            model_name='clearedreserveup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
