# Generated by Django 3.2.5 on 2021-07-18 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_auto_20210718_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearedreserveup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 17, 23, 35, 123063, tzinfo=utc)),
        ),
    ]
