# Generated by Django 3.2.5 on 2021-07-18 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_alter_clearedreserveup_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearedreserveup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 17, 54, 34, 893635, tzinfo=utc)),
        ),
    ]
