# Generated by Django 3.2.5 on 2021-07-18 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_alter_clearedreserveup_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearedreserveup',
            name='time_block',
            field=models.CharField(default='NoTime', max_length=20),
        ),
        migrations.AlterField(
            model_name='clearedreserveup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 18, 5, 10, 886079, tzinfo=utc)),
        ),
    ]
