# Generated by Django 3.2.5 on 2021-07-18 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_auto_20210718_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearedreservedown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 18, 15, 20, 990764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clearedreserveup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 18, 15, 20, 930254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clearentitydown',
            name='clearedreserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.clearedreservedown'),
        ),
    ]
