# Generated by Django 3.2.5 on 2021-07-22 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_auto_20210718_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearedreservedown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 10, 57, 1, 794812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clearedreserveup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 10, 57, 1, 682292, tzinfo=utc)),
        ),
    ]
