# Generated by Django 3.2.5 on 2021-07-22 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0014_auto_20210722_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearedreservedown',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 22)),
        ),
        migrations.AddField(
            model_name='clearedreservedown',
            name='is_dat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearedreservedown',
            name='is_rtm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearedreserveup',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 22)),
        ),
        migrations.AddField(
            model_name='clearedreserveup',
            name='is_dat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearedreserveup',
            name='is_rtm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clearedreservedown',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 13, 8, 13, 966332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clearedreserveup',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 13, 8, 13, 886318, tzinfo=utc)),
        ),
    ]
