# Generated by Django 3.2.5 on 2021-07-23 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0015_auto_20210722_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearedreservedown',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clearedreservedown',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clearedreserveup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clearedreserveup',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
